"""This file is generated by setuptools-generate.
The information comes from pyproject.toml.
It provide some metainfo for docs/conf.py to build documents and
help2man to build man pages.
"""

# For docs/conf.py
project = "tmux-bitahub"
author = """Wu Zhenyu <wuzhenyu@ustc.edu> """
copyright = "2023"

# For help2man
DESCRIPTION = "Display bitahub GPU status in tmux status line"
EPILOG = "Report bugs to https://github.com/Freed-Wu/tmux-bitahub/issues"
# format __version__ by yourself
VERSION = """tmux-bitahub {__version__}
Copyright (C) 2023
Written by Wu Zhenyu <wuzhenyu@ustc.edu> """
